Template develop
electronic-structure/SIRIUS pull request #646
Opened 2021-06-11 21:50 UTC by manhin321

Template Gvec class and Wave_functions class

2021-06-14 12:06 UTC, toxa81 commented
@manhin321 What is the use case for templated G-vector class? From what I see, it's only the Cartesian components and length are affected.

2021-06-14 13:19 UTC, manhin321 commented
> @manhin321 What is the use case for templated G-vector class? From what I see, it's only the Cartesian components and length are affected.

It was originally intended to template everything inside the Wave_functions class to allow full fp32 calculation including the unit cell matrix storage. This change would indeed create overhead for copying when doing mix-precision calculation. 
We can still allow the templated version of Gvec class but always use Gvec<double> to see the difference later

2021-06-14 13:26 UTC, toxa81 commented
Still, I want to argue that wave-functions in FP32 can co-exist with the G-vector Cartesian coordinates in FP64. You will use the G^2/2 as a kinetic energy term, and this can be contained inside Local_operator class.

2021-06-14 13:32 UTC, manhin321 commented
I agree with that. I just take reference from the Julia dftk code to propose the change. Otherwise, I try to roll back for non templated Gvec class version

2021-06-18 07:24 UTC, toxa81 commented
> I agree with that. I just take reference from the Julia dftk code to propose the change. Otherwise, I try to roll back for non templated Gvec class version

Yes, Gvec should be rolled back to it's original non-templated version.

2021-06-18 08:44 UTC, toxa81 requested changes
A lot of changes come from templated G-vector class. I propose to revert it back to non-templated class.

2021-06-18 08:44 UTC, toxa81 commented on src/band/residuals.cpp
>  compute_residuals(sddk::memory_t mem_type__, sddk::spin_range spins__, int num_bands__, sddk::mdarray<double, 1>& eval__,
Shouldn't it be templated over Wave_function type?

2021-06-18 13:48 UTC, closed without merging