Hubbard U+V
electronic-structure/SIRIUS pull request #673
Opened 2021-08-17 14:19 UTC by mtaillefumier

- Implemented the U+V term for colinear case
- Add missing reduction over k-points when calculating non-local occupation numbers
- Symmetrize the local occupation numbers
- Add yet another test case for NiO (with the 12 bonds for the +V term)
- Reorganized the calculations of the occupancies deriatives (hopefully it is clearer now)

- TODO : consider the full set of orboitals when orthogonalizing the hubbard wave functions.
- TODO : add fortran interface and extensive tests with QE

- the diff is long because of formatting.

2021-08-23 09:20 UTC, toxa81 commented on src/geometry/force.cpp
> +            auto z1 = std::exp(double_complex(0, -twopi * dot(Ttot, kp__.vk())));
dot() works on 3d-vectors of different type, so  `vector3d<double> Ttot` is not needed

2021-08-23 09:22 UTC, toxa81 commented on src/hamiltonian/non_local_operator.hpp
> +          auto z1 = std::exp(double_complex(0, twopi * dot(Ttot, vk_)));
same here, dot() can take vector3d of different types

2021-08-23 09:23 UTC, toxa81 commented on src/hamiltonian/non_local_operator.hpp
> +  vector3d<T> &vk() {
formatting
```
vector3d<T> vk()
{
    return vk_;
}
```

2021-08-25 07:31 UTC, toxa81 requested changes
Just a few minor corrections are required

2021-09-02 12:16 UTC, mtaillefumier commented
I am going to close this PR since I rewrote it from scratch

2021-09-02 12:16 UTC, closed without merging