Uplus v2
electronic-structure/SIRIUS pull request #677
Opened 2021-09-02 12:29 UTC by mtaillefumier

This PR includes all necessary bit of code to run simulations with the LDA+U+V correction and more. It includes so far

- Multi-orbital case for both U and V corrections
- Possibility to orthogonalize the hubbard subspace compared to all atomic wave functions
- Forces (for U+V) and stresses for the co-linear case
- 3 more tests for testing the code

Remains to be done

- [ ] Move symmetrization of the occupations matrices to the right place (the function would need too many parameters, so need a proper fix for this)
- [x] Add a function for adding atom pairs for the V term in the api
- [x] Extra work on QE side
- [ ] And of course more testing
- [x] remove duplicated code for finding the orbital index

The multi-orbital case is treated such that the code keep a list of "atomic" levels to be considered in the U (and / or V) term. So instead of having occupations numbers per atoms we have occupations numbers per atomic levels. This would be equivalent to having a full matrix that we decompose per block, each block representing a term in the correction.

2021-09-08 12:17 UTC, toxa81 commented on src/api/sirius_api.cpp
> +      doc: J0 for the simple interaction treatment.
copy-paste is wrong

2021-11-25 13:50 UTC, toxa81 requested changes

2021-11-25 13:50 UTC, toxa81 commented on src/hubbard/hubbard_matrix.cpp
> +        int size__ = 0;
local variables do not have tailing underscores

2021-11-25 13:50 UTC, toxa81 commented on src/mixer/mixer_functions.cpp
> +          y.nonlocal(link)[i] *= alpha * x.nonlocal(link)[i] + y.nonlocal(link)[i];
why *= here instead of = ?

2021-11-25 13:50 UTC, toxa81 commented on verification/test12/output_ref.json
> +            "total": -146.56055311695883,
change in total energy from `-147.35305830650776`

2021-11-25 13:50 UTC, toxa81 commented on verification/test13/output_ref.json
> +            "total": -42.27968211789244,
change in total energy from `-43.07007257816769`

2021-11-25 13:50 UTC, toxa81 commented on verification/test22/output_ref.json
> +            "total": -375.4010540846649,
change in total energy from `-377.2823257239195`

2021-12-13 07:33 UTC, mtaillefumier commented
I had to revert two patch (the last two) because I could not find the error. things seem to behave now.

2022-02-17 16:29 UTC, closed without merging