Constrained Hubbard
electronic-structure/SIRIUS pull request #917
Opened 2023-11-07 17:40 UTC by mtaillefumier

this PR implements the hubbard constrained calculations in SIRIUS. The non-colinear case is not covered in this PR (although it will work). Including it is not difficult but we need to include complex support in the input file schema and do some simple changes to the code. 
The method can be run either with constraining the occupation alone but neglecting the energy correction to the total energy or actually properly minimize the hamiltonian with a proper treatment of the constraints.
The interface is also modified to account for these changes.

2023-11-10 13:47 UTC, toxa81 requested changes
There is really one change related to naming of one of the hubbard methods and idntation level of omp pragmas

2023-11-10 16:39 UTC, mtaillefumier commented
I do not mind enforcing indentation but please merge the formatting PR first then I can fix all these needy greedy formatting errors.

2023-11-10 17:34 UTC, mtaillefumier commented on src/context/simulation_parameters.hpp
> +      return cfg().hubbard().constrained_hubbard_calculation();
i simplified all new hubbard options.

2023-11-11 14:59 UTC, toxa81 commented
@mtaillefumier we should do the opposite - merge this first, then apply formatting

2023-11-11 17:13 UTC, mtaillefumier commented
I still have two things to fix

- the order of the Ylm between sirius and qe
- q-e-sirius is buggy right now. Some problem with the interface

2023-11-14 10:13 UTC, mtaillefumier commented
I think I fixed all remaining issues. pure QE is buggy with original implementation and only converges after 151 iterations while q-e-sirius converges after 31 iterations.

2023-11-15 20:57 UTC, toxa81 commented
@mtaillefumier ci/cd passes, so it's good from my side. OK to merge?

2023-11-16 06:52 UTC, mtaillefumier commented
let's merge.

2023-11-16 11:11 UTC, merged