Python updates
electronic-structure/SIRIUS pull request #968
Opened 2024-02-22 21:49 UTC by simonpintarelli

2024-03-05 10:08 UTC, toxa81 requested changes

2024-03-05 10:08 UTC, toxa81 commented on src/context/config.hpp
@simonpintarelli generating script should be updated, config.hpp should not be hand-crafted.

2024-03-05 17:42 UTC, simonpintarelli commented on src/context/config.hpp
I've reverted it. Seems my previous comment disappeared.

2024-03-06 06:05 UTC, toxa81 approved these changes
LGTM

2024-03-06 06:06 UTC, merged