python updates
electronic-structure/SIRIUS pull request #976
Opened 2024-03-16 23:34 UTC by simonpintarelli

- fix / cleanup of nlcg python
- add new pytest

2024-04-30 09:38 UTC, toxa81 commented
@simonpintarelli please have a look at the comment about `has_augmented_atom()`. Otherwise it's good to go

2024-04-30 09:41 UTC, simonpintarelli commented
@toxa81 which comment?

2024-04-30 10:01 UTC, toxa81 requested changes

2024-04-30 10:01 UTC, toxa81 commented on src/unit_cell/unit_cell.hpp
> +    has_augmented_atom() const
Unit_cell::augment() provides same functionality

2024-04-30 10:01 UTC, toxa81 commented on src/unit_cell/unit_cell.hpp
> +    has_augmented_atom() const
@simonpintarelli here

2024-04-30 17:20 UTC, simonpintarelli commented on src/unit_cell/unit_cell.hpp
> +    has_augmented_atom() const
Thanks. I've removed my duplicate.

2024-05-30 14:08 UTC, toxa81 approved these changes
LGTM

2024-05-30 14:09 UTC, merged